//! Signal domain model for intelligence alerts and external indicators

use serde::{Deserialize, Serialize};
use chrono::{DateTime, Utc};
use uuid::Uuid;

/// Signal strength classification
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SignalStrength {
    Weak,
    Moderate,
    Strong,
    Critical,
}

/// Signal category for classification
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SignalCategory {
    Market,
    Political,
    Economic,
    Social,
    Geopolitical,
    Regulatory,
    Commodity,
    Currency,
    Technology,
    Security,
}

/// Internal signal generated by Hermes analysis
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Signal {
    pub id: Uuid,
    pub title: String,
    pub description: String,
    pub category: SignalCategory,
    pub strength: SignalStrength,
    pub confidence_score: f64, // 0.0 to 1.0
    pub source_article_ids: Vec<Uuid>,
    pub related_actors: Vec<Uuid>,
    pub related_topics: Vec<Uuid>,
    pub metadata: serde_json::Value,
    pub created_at: DateTime<Utc>,
    pub expires_at: Option<DateTime<Utc>>,
}

/// External signal from third-party sources
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExternalSignal {
    pub id: Uuid,
    pub source: String, // e.g., "Bloomberg", "Reuters", "Yahoo Finance"
    pub external_id: String, // Original ID from source system
    pub signal_type: String, // e.g., "price_alert", "news_alert", "economic_indicator"
    pub title: String,
    pub description: String,
    pub category: SignalCategory,
    pub strength: SignalStrength,
    pub confidence_score: f64,
    pub raw_data: serde_json::Value, // Original payload from external source
    pub processed_at: DateTime<Utc>,
    pub received_at: DateTime<Utc>,
    pub is_processed: bool,
}

impl Signal {
    /// Create a new internal signal
    pub fn new(
        title: String,
        description: String,
        category: SignalCategory,
        strength: SignalStrength,
    ) -> Self {
        Self {
            id: Uuid::new_v4(),
            title,
            description,
            category,
            strength,
            confidence_score: 0.5,
            source_article_ids: Vec::new(),
            related_actors: Vec::new(),
            related_topics: Vec::new(),
            metadata: serde_json::json!({}),
            created_at: Utc::now(),
            expires_at: None,
        }
    }

    /// Set confidence score (0.0 to 1.0)
    pub fn with_confidence(mut self, score: f64) -> Self {
        self.confidence_score = score.max(0.0).min(1.0);
        self
    }

    /// Add source article IDs
    pub fn with_sources(mut self, article_ids: Vec<Uuid>) -> Self {
        self.source_article_ids = article_ids;
        self
    }

    /// Add related entities
    pub fn with_relations(mut self, actors: Vec<Uuid>, topics: Vec<Uuid>) -> Self {
        self.related_actors = actors;
        self.related_topics = topics;
        self
    }

    /// Set expiration time
    pub fn with_expiration(mut self, expires_at: DateTime<Utc>) -> Self {
        self.expires_at = Some(expires_at);
        self
    }

    /// Add metadata
    pub fn with_metadata(mut self, metadata: serde_json::Value) -> Self {
        self.metadata = metadata;
        self
    }

    /// Check if signal is expired
    pub fn is_expired(&self) -> bool {
        self.expires_at
            .map(|exp| Utc::now() > exp)
            .unwrap_or(false)
    }

    /// Check if signal is high priority (Strong or Critical)
    pub fn is_high_priority(&self) -> bool {
        matches!(self.strength, SignalStrength::Strong | SignalStrength::Critical)
    }

    /// Check if signal is Indonesian market related
    pub fn is_indonesian_market_signal(&self) -> bool {
        matches!(
            self.category,
            SignalCategory::Market | SignalCategory::Economic | SignalCategory::Commodity | SignalCategory::Currency
        ) || self.title.to_lowercase().contains("indonesia")
            || self.description.to_lowercase().contains("indonesia")
            || self.description.to_lowercase().contains("rupiah")
            || self.description.to_lowercase().contains("idx")
    }
}

impl ExternalSignal {
    /// Create a new external signal
    pub fn new(
        source: String,
        external_id: String,
        signal_type: String,
        title: String,
        description: String,
        category: SignalCategory,
        raw_data: serde_json::Value,
    ) -> Self {
        let now = Utc::now();
        Self {
            id: Uuid::new_v4(),
            source,
            external_id,
            signal_type,
            title,
            description,
            category,
            strength: SignalStrength::Moderate,
            confidence_score: 0.5,
            raw_data,
            processed_at: now,
            received_at: now,
            is_processed: false,
        }
    }

    /// Set signal strength and confidence
    pub fn with_assessment(mut self, strength: SignalStrength, confidence: f64) -> Self {
        self.strength = strength;
        self.confidence_score = confidence.max(0.0).min(1.0);
        self
    }

    /// Mark as processed
    pub fn mark_processed(mut self) -> Self {
        self.is_processed = true;
        self.processed_at = Utc::now();
        self
    }

    /// Convert to internal Signal
    pub fn to_internal_signal(&self) -> Signal {
        Signal::new(
            self.title.clone(),
            format!("External: {} - {}", self.source, self.description),
            self.category.clone(),
            self.strength.clone(),
        )
        .with_confidence(self.confidence_score)
        .with_metadata(serde_json::json!({
            "external_source": self.source,
            "external_id": self.external_id,
            "signal_type": self.signal_type,
            "raw_data": self.raw_data
        }))
    }

    /// Check if signal is from Indonesian sources
    pub fn is_indonesian_source(&self) -> bool {
        let source_lower = self.source.to_lowercase();
        source_lower.contains("indonesia") ||
        source_lower.contains("idx") ||
        source_lower.contains("kompas") ||
        source_lower.contains("detik") ||
        source_lower.contains("tempo") ||
        source_lower.contains("antara")
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Duration;

    #[test]
    fn test_signal_creation() {
        let signal = Signal::new(
            "BMRI Price Alert".to_string(),
            "BMRI stock price increased by 5%".to_string(),
            SignalCategory::Market,
            SignalStrength::Strong,
        );

        assert_eq!(signal.title, "BMRI Price Alert");
        assert_eq!(signal.category, SignalCategory::Market);
        assert_eq!(signal.strength, SignalStrength::Strong);
        assert_eq!(signal.confidence_score, 0.5);
        assert!(signal.id.to_string().len() > 0);
    }

    #[test]
    fn test_signal_with_confidence() {
        let signal = Signal::new(
            "Test Signal".to_string(),
            "Test".to_string(),
            SignalCategory::Economic,
            SignalStrength::Moderate,
        )
        .with_confidence(0.85);

        assert_eq!(signal.confidence_score, 0.85);

        // Test bounds checking
        let signal2 = Signal::new(
            "Test".to_string(),
            "Test".to_string(),
            SignalCategory::Economic,
            SignalStrength::Moderate,
        )
        .with_confidence(1.5); // Should be clamped to 1.0

        assert_eq!(signal2.confidence_score, 1.0);
    }

    #[test]
    fn test_signal_expiration() {
        let future_time = Utc::now() + Duration::hours(1);
        let past_time = Utc::now() - Duration::hours(1);

        let active_signal = Signal::new(
            "Active Signal".to_string(),
            "Test".to_string(),
            SignalCategory::Market,
            SignalStrength::Moderate,
        )
        .with_expiration(future_time);

        assert!(!active_signal.is_expired());

        let expired_signal = Signal::new(
            "Expired Signal".to_string(),
            "Test".to_string(),
            SignalCategory::Market,
            SignalStrength::Moderate,
        )
        .with_expiration(past_time);

        assert!(expired_signal.is_expired());
    }

    #[test]
    fn test_signal_priority() {
        let high_priority = Signal::new(
            "Critical Alert".to_string(),
            "Test".to_string(),
            SignalCategory::Market,
            SignalStrength::Critical,
        );
        assert!(high_priority.is_high_priority());

        let low_priority = Signal::new(
            "Weak Signal".to_string(),
            "Test".to_string(),
            SignalCategory::Market,
            SignalStrength::Weak,
        );
        assert!(!low_priority.is_high_priority());
    }

    #[test]
    fn test_indonesian_market_signal() {
        let market_signal = Signal::new(
            "IDX Market Update".to_string(),
            "Indonesian stock market analysis".to_string(),
            SignalCategory::Market,
            SignalStrength::Moderate,
        );
        assert!(market_signal.is_indonesian_market_signal());

        let currency_signal = Signal::new(
            "Global News".to_string(),
            "Rupiah strengthens against USD".to_string(),
            SignalCategory::Social,
            SignalStrength::Moderate,
        );
        assert!(currency_signal.is_indonesian_market_signal());
    }

    #[test]
    fn test_external_signal_creation() {
        let external_signal = ExternalSignal::new(
            "Bloomberg".to_string(),
            "BLB123456".to_string(),
            "price_alert".to_string(),
            "INCO Price Movement".to_string(),
            "Nickel prices surge affecting INCO".to_string(),
            SignalCategory::Commodity,
            serde_json::json!({"price": 25000, "change": 0.05}),
        );

        assert_eq!(external_signal.source, "Bloomberg");
        assert_eq!(external_signal.signal_type, "price_alert");
        assert!(!external_signal.is_processed);
    }

    #[test]
    fn test_external_signal_processing() {
        let external_signal = ExternalSignal::new(
            "Yahoo Finance".to_string(),
            "YF789".to_string(),
            "earnings_alert".to_string(),
            "BBRI Earnings".to_string(),
            "BBRI reports strong Q4 earnings".to_string(),
            SignalCategory::Market,
            serde_json::json!({"earnings_per_share": 850}),
        )
        .with_assessment(SignalStrength::Strong, 0.9)
        .mark_processed();

        assert!(external_signal.is_processed);
        assert_eq!(external_signal.strength, SignalStrength::Strong);
        assert_eq!(external_signal.confidence_score, 0.9);
    }

    #[test]
    fn test_external_to_internal_conversion() {
        let external_signal = ExternalSignal::new(
            "Detik".to_string(),
            "DTK456".to_string(),
            "news_alert".to_string(),
            "Mining Policy Change".to_string(),
            "New mining regulations announced".to_string(),
            SignalCategory::Regulatory,
            serde_json::json!({"regulation_id": "REG2026001"}),
        );

        let internal_signal = external_signal.to_internal_signal();

        assert_eq!(internal_signal.category, SignalCategory::Regulatory);
        assert!(internal_signal.description.contains("External: Detik"));
        assert!(internal_signal.metadata["external_source"] == "Detik");
    }

    #[test]
    fn test_indonesian_source_detection() {
        let indonesian_signal = ExternalSignal::new(
            "Kompas".to_string(),
            "KMP123".to_string(),
            "news_alert".to_string(),
            "Economic Update".to_string(),
            "Indonesian economic indicators".to_string(),
            SignalCategory::Economic,
            serde_json::json!({}),
        );
        assert!(indonesian_signal.is_indonesian_source());

        let foreign_signal = ExternalSignal::new(
            "Reuters".to_string(),
            "RTR789".to_string(),
            "news_alert".to_string(),
            "Global Markets".to_string(),
            "Global market analysis".to_string(),
            SignalCategory::Market,
            serde_json::json!({}),
        );
        assert!(!foreign_signal.is_indonesian_source());
    }
}